version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - run:
          name: Clone repo
          command: git clone https://github.com/martino-vic/copius_api.git
      - run:
          name: "Install Deps"
          command: pip install --user -r requirements.txt
          
      - run:
          name: "python/test"
          command: python -m unittest discover -v

workflows:
  main:
    jobs:
      - build
      
