build-and-test-cov-win:
    #environment: PYTHONPATH=./tmp
    
    #executor: win/default # executor type
    executor:
      name: win/default
      shell: powershell.exe
    steps:

      - checkout
      - run:
          name: "Install Python"
          command: choco install python --version=3.7.9
      #- python/install-deps
      - run:
          name: "Install Deps"
          command: pip install --user -r requirements.txt
          
      - run:
          name: "python/test"
          command: python -m unittest discover -v
