version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
         command: cd C:\Users\Viktor\OneDrive\Git\copius\tests
         shell: cmd.exe
